# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '.*\/static\/.*$'
      - id: check-added-large-files
        exclude: '.*\/static\/.*$'
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: double-quote-string-fixer

  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        exclude: '.*\/ml\/.*$'

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8
        args: [--in-place]
        exclude: '.*\/ml\/.*$'
